### ISSUE TITLE
Service dashboard reporting 1 node even though there aren't any nodes

### ISSUE THREAD

**Issue by williewheeler** [ExpediaDotCom/seiso#118]
This is in the service instance list's health column: "0 of 1 healthy". It says this even when the service instance has no nodes.

**Comment by williewheeler** [comment]
The underlying query uses a bunch of left outer joins. I haven't looked into this bug, but probably it's generating a single result row even when there aren't any nodes.

**Comment by janakiramvit** [comment]
can you please post the link of the issue here, i mean the issue that you observe on the website..

**Comment by williewheeler** [comment]
Try reproducing it locally. Create a service instance without any nodes and see whether the issue arises.

**Comment by launchcg-ztonia** [comment]
Testing issue with MySQL 5.7, sql mode ONLY_FULL_GROUP_BY. Not seeing the problem. Trying with the setting disabled. Still a non-issue.

Also attempted with Mariadb 10. Query resolves as 0 out of 0, NA. Which seems a very sensible result.

**Comment by williewheeler** [comment]
Zaal, next time you're in the office, let me show you on the live site what we're seeing. It occurs for any service instance that doesn't have any nodes.

**Comment by williewheeler** [comment]
**Update.** Not seeing this issue in the v3 UI. Maybe it was a UI issue rather than an API issue. At any rate let's keep this open for a bit and if it doesn't resurface then we can close it.

**Comment by williewheeler** [comment]
Closing issue. If it recurs we can reopen.
