### ISSUE TITLE
On service details page, make it more obvious which service instances are "in progress" during deployment

### ISSUE THREAD

**Issue by williewheeler** [ExpediaDotCom/seiso#140]
During deployments, the nodes have health status as "upgrade needed" (at least with Eos health statuses), but this gets lost in two places:

1) on the service instance details donut chart, which Mike Nash would like us to fix, and
2) on the service details page, which Ivan Chu would like us to fix to make it easier to follow along with deployments.

**Comment by williewheeler** [comment]
TODO Migrate to UI

**Comment by imccunn** [comment]
Migrated to seiso-ui repo.
