### ISSUE TITLE
AD/LDAP Import - Use Display Name If Set

### ISSUE THREAD

**Issue by brownc** [ExpediaDotCom/seiso#147]
Right now, we're pulling out the full name (or "fn sn") from AD.  Some companies (EI included) insist of AD reflecting your full mammoth name, and for some of us that sucks.

Thus, when importing from AD/LDAP we should use DisplayName if set, and then fall back to current if not.

**Comment by brownc** [comment]
Looking at this, I can see a threefold change need:

1) Update schema to accept "display_name" field
2) Update seiso-import-ldap to grab display_name and push up
3) Update seiso UI where a person is reference to do something like "if person.display_name then person.display_name else (person.first_name + ' ' + person.last_name)

I'll discuss 1 with Willie, can perform 2 myself once available and will need Willie again for 3.

**Comment by andreihalici** [comment]
Hello, 

This issues seems to be a duplicate/clone of #137

**Comment by brownc** [comment]
Hey Andrei - yes and no.  137 is around not showing the Alias, but using a name.  Right now the UI does have some places (like a Service Owner for example) where the name is used.  However it's a combination of "fn sn", which for someone like me sucks.  I have a "displayname" set shortening my first name - and thus we should use that in all places.  If we take existing code to replace the aliases from 137, we're still not going to be honouring users's display preferences in AD for their name.

This is all assuming I've read 137 correctly :D

**Comment by williewheeler** [comment]
Done
