### ISSUE TITLE
Seiso Service Instance name 40 character length

### ISSUE THREAD

**Issue by launchcg-ztonia** [ExpediaDotCom/seiso#168]
**Problem.** Maximum Service Instance name appears to be 40 characters.This may be too short to accomodate the instance naming convention {SERVICENAME}-{ENVIRONMENTNAME}.

This change will allow Hypgnosis to auto-generate service instance names per the convention above.

**Acceptance criteria.** Seiso allows service instance names up to 120 characters. (80 characters wouldn't accommodate the convention above, and 81 characters is too weird for a limit. Therefore 120. characters.)

**Comment by williewheeler** [comment]
Done.
