### ISSUE TITLE
Minor bug - page title at times shows 'search results' on seiso UI

### ISSUE THREAD

**Issue by venkatamamidi** [ExpediaDotCom/seiso#192]
At times when I refresh the seiso UI (i have at least seen this happen for service instance page, mostly when i refresh an existing page) i see the page title as 'Search Results - Seiso' instead of the actual service instance name.

**Comment by williewheeler** [comment]
Acknowledged. I've seen this too. This may end up disappearing after we release the updated UI. But I'll keep this ticket around just to make sure we verify.
