### ISSUE TITLE
Adding support for annotated health states 

### ISSUE THREAD

**Issue by wildlyadequate** [ExpediaDotCom/seiso#193]
Add the ability to display details regarding a health state, whether it be text or a link to another resource, such as a particular Splunk log/report.

Server:
1.  Change the data model to support an AnnotatedHealthState object
2.  Refactor the codebase in response to the data model change
3.  [Possible] offer endpoint CRUD access for the AnnotatedHealthState entity
Client
1.  Select and display details on the Node details pane

**Comment by wildlyadequate** [comment]
Add the ability to display details regarding a health state, whether it be text or a link to another resource, such as a particular Splunk log/report.

Server:
1.  Change the data model to support an AnnotatedHealthState object
2.  Refactor the codebase in response to the data model change
3.  [Possible] offer endpoint CRUD access for the AnnotatedHealthState entity
Client
1.  Select and display details on the Node details pane

**Comment by wildlyadequate** [comment]
Willie said that server(3) was unnecessary, because we shouldn't allow an agent to query for all AnnotatedHealthStates - they will always be requested in the context of a Node.

**Comment by williewheeler** [comment]
Re (3) above: more like right now there's no use case for repo access, and so I don't want to commit the API to supporting that at this time. If such a use case emerges then of course we would add the repo.

**Comment by williewheeler** [comment]
Also, we are going to need to coordinate this with Eos as it will be a breaking change.

**Comment by williewheeler** [comment]
Done
