### ISSUE TITLE
Remove default XML converter/marshalling mechanism included with SDR

### ISSUE THREAD

**Issue by imccunn** [ExpediaDotCom/seiso#196]
**Problem:** When the client requests `text/xml` via the `Accept` header for https://seiso.example.com/api/serviceInstances/123/healthBreakdown, the service responds with an HTTP 500. This is because Spring Data REST by default includes a JAXB-based HTTP message converter, and it fails when it tries to de/serialize POJOs that don't have the JAXB annotations.

    Could not marshal [Resources { content: [BreakdownItem(statusName=Unknown, statusType=warning, count=10)], links: [<https://seiso.example.com/api/serviceInstances/123/healthBreakdown>;rel="self", <https://seiso.example.com/api/serviceInstances/123/healthBreakdown>;rel="up"] }]: null; nested exception is javax.xml.bind.MarshalException - with linked exception: [com.sun.istack.internal.SAXException2: unable to marshal type "com.expedia.seiso.web.resource.BreakdownItem" as an element because it is missing an @XmlRootElement annotation]

**Acceptance criteria:** Client can request `text/xml` without generating a 500. If the client accepts *only* `text/xml` then the API should respond appropriately (HTTP 406). Otherwise the API should just run down the line. But not HTTP 500.

**Comment by williewheeler** [comment]
Reclassified this as a bug, because there shouldn't be a server error when the client requests text/xml.

**Comment by williewheeler** [comment]
Done. Thanks Ed.
