### ISSUE TITLE
Minor UI behavior change request - when Node doesn't exist

### ISSUE THREAD

**Issue by venkatamamidi** [ExpediaDotCom/seiso#199]
Currently, when you attempt to access a node which doesn't exist in UI, you get a nice popup which says 'Error while getting the node' but once you click 'Ok', you still see the spinner image appearing like it's doing something. Would be nice if the behavior can be same as non-existent 'service-instance' page. (You rather see the 'Couldn't get the service instance' message directly on the page instead of the popup, and no spinner).

**Comment by williewheeler** [comment]
Migrated to https://github.com/ExpediaDotCom/seiso-ui/issues/141
