### ISSUE TITLE
Add query to return service instance nodes by health status

### ISSUE THREAD

**Issue by williewheeler** [ExpediaDotCom/seiso#202]
**Problem.** Client needs to be able to get all healthy nodes for a given large service instance, and would like to avoid n+1 selects here.

**Acceptance criteria.** Client can get the healthy nodes by page. While this is still linear in the number of nodes, it's a much smaller number of requests.

**Technical approach.** One approach would be to use a projection exposing the nodes' health status, and that would work. However it will be much tighter to implement this as a repository query, as there will fewer rows and less data per row. Finding nodes by health status seems to be of sufficient generality to justify adding a query here.

**Comment by williewheeler** [comment]
Done

**Comment by brownc** [comment]
Beautiful, thank you very much Willie!
