### ISSUE TITLE
Implement optimistic locking for nodes

### ISSUE THREAD

**Issue by williewheeler** [ExpediaDotCom/seiso#222]
**Problem.** When a client sends multiple health status updates to Seiso in rapid succession, sometimes they arrive at the Seiso database out of order (race condition). This causes Seiso to report the incorrect status.

**Acceptance criteria.** Seiso implements optimistic locking for nodes. Whatever mechanism we use here needs to generalize to other resources as well, but for now all we care about is nodes.

**Technical approach.** Use Spring Data REST ETag-based optimistic locking:

http://docs.spring.io/spring-data/rest/docs/current/reference/html/#conditional
http://stackoverflow.com/questions/2572566/java-jpa-version-annotation

**Comment by launchcg-ztonia** [comment]
This issue should now be resolved for node health status by commit
4920340e1c0e7f062306d819364a4f9e70967d94
