### ISSUE TITLE
Popovers have wrong z-order

### ISSUE THREAD

**Issue by williewheeler** [ExpediaDotCom/seiso#71]
Popovers are appearing over the nav bar:

![Screenshot](http://i.imgur.com/GQ2gWK6.png)

**Comment by williewheeler** [comment]
It doesn't look so bad from the screenshot, but when you scroll the page up, the popover becomes disconnected from its target: the popover appears above the navbar and the target underneath it.

**Comment by williewheeler** [comment]
TODO Migrate to UI. This may not be an issue anymore.

**Comment by imccunn** [comment]
Migrated to seiso-ui repo.
